sudo: require
services:
  - docker

before_install:
  - docker build -t gg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gg/docker-react npm run test -- --coverage

language: generic

deploy:
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-615120079561"
  backet_path: "docker"
  on:
    brench: master
